#Bài tập 1: Thao tác với ma trận  
**Lý thuyết**:  
NumPy cung cấp các công cụ mạnh mẽ để thao tác ma trận, bao gồm tính toán các định thức, tìm nghịch đảo và tính toán các giá trị riêng và vectơ riêng.
  
**Đề bài**:  
Tạo ma trận 5x5 ngẫu nhiên và thực hiện các thao tác sau:  
* Tính định thức (determinant) của ma trận.  
* Tìm nghịch đảo (transpose) của ma trận.  
* Tính các giá trị riêng (eigent value) và vectơ riêng (eigent vector) của ma trận.   
(Phần này sẽ liên quan tới đại số tuyến tính, mọi người có thể tự tìm hiểu để hiểu chi tiết về các khái niệm trên)

<details>
  <summary>Hint</summary>

```python
import numpy as np

# Generate a random 5x5 matrix
matrix = np.random.rand(5, 5)

# Compute determinant
det = np.linalg.det(matrix)

# Find inverse
inverse = np.linalg.inv(matrix)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

```
</details>

In [17]:
# Your code here
import numpy as np

# Create 5x5 random matrix
np.random.seed(0)
np_array = np.random.randint(1, 10, (5, 5))
print("Numpy matrix:", np_array)

# Calculate determinant of the matrix
det = np.linalg.det(np_array)
print("Determinant: ", det)

# Find transpose of the matrix
transpose = np.transpose(np_array)
print("Transpose:", transpose)

# Calculate eigent value and eigent vector of the matrix
eigen_values, eigen_vectors = np.linalg.eig(np_array)
print("Eigen values:", eigen_values)
print("Eigen vectors:", eigen_vectors)


Numpy matrix: [[6 1 4 4 8]
 [4 6 3 5 8]
 [7 9 9 2 7]
 [8 8 9 2 6]
 [9 5 4 1 4]]
Determinant:  -1553.0000000000011
Transpose: [[6 4 7 8 9]
 [1 6 9 8 5]
 [4 3 9 9 4]
 [4 5 2 2 1]
 [8 8 7 6 4]]
Eigen values: [26.83758108+0.j         -5.72750148+0.j          2.67642836+0.j
  1.60674602+1.09237488j  1.60674602-1.09237488j]
Eigen vectors: [[-0.36083382+0.j         -0.55742483+0.j          0.27993019+0.j
   0.08352756+0.16627059j  0.08352756-0.16627059j]
 [-0.40972264+0.j         -0.41400418+0.j         -0.0591885 +0.j
   0.12583732-0.03257038j  0.12583732+0.03257038j]
 [-0.54542581+0.j          0.17952207+0.j         -0.56080735+0.j
  -0.48046568-0.22212425j -0.48046568+0.22212425j]
 [-0.53053793+0.j          0.31325133+0.j         -0.61263134+0.j
  -0.65740724+0.j         -0.65740724-0.j        ]
 [-0.35066581+0.j          0.62251388+0.j          0.4778219 +0.j
   0.48463334+0.03523023j  0.48463334-0.03523023j]]


# Bài tập 2: Optimization
**Lý thuyết:**  
Gradient descent là một thuật toán tối ưu hóa được sử dụng để cực tiểu hóa hàm bằng cách di chuyển lặp đi lặp lại theo hướng dốc xuống.

**Đề bài:**  
Triển khai gradient descent sử dụng NumPy để tối ưu hàm số sau:
 $$ f(x) = x^2 + 5 \sin(x) $$
<details>
  <summary>Hint</summary>

```python
import numpy as np

def gradient_descent(x, learning_rate, iterations):
    for _ in range(iterations):
        gradient = 2*x + 5*np.cos(x)  # Đạo hàm riêng theo x
        x = x - learning_rate * gradient # Cập nhật tham số
    return x

# Khởi tạo các hyperparameters
x_initial = 5  # Input đầu vào
learning_rate = 0.1 # Tốc độ học
iterations = 100 # Số lần lặp

# Run gradient descent
minima = gradient_descent(x_initial, learning_rate, iterations)
```

</details>

In [18]:
# Your code here
# Deploying gradient descent using numpy

def gradient_descent(x0, learning_rate, ite):
    x = x0
    for i in range(ite):
        # Calculate gradient
        grad = 2*x + 5*np.cos(x)
        x = x - learning_rate * grad
    return x

x0 = 10
learning_rate = 0.1
ite = 100

x_optimal = gradient_descent(x0, learning_rate, ite)
print("Optimal x:", x_optimal)


Optimal x: -1.110510503581112


# Bài tập 3: Phân tích thống kê  
**Lý thuyết**:  
NumPy cung cấp các chức năng để phân tích thống kê, bao gồm tính toán giá trị trung bình (mean), trung vị (median), độ lệch chuẩn (standard deviation) và mối tương quan (correlation).  

**Đề Bài**:  
Thực hiện phân tích thống kê trên tập dữ liệu bai3.csv bằng NumPy:  
* Tính giá trị trung bình, trung vị và độ lệch chuẩn của tập dữ liệu.
* Tính toán ma trận tương quan giữa các biến khác nhau.
* Xác định các ngoại lệ trong tập dữ liệu bằng cách sử dụng điểm z.

<details>
  <summary>Hint</summary>

```python
  # Load dataset
  data = np.loadtxt('dataset.csv', delimiter=',')

  # Calculate mean, median, and standard deviation
  mean = np.mean(data, axis=0)
  median = np.median(data, axis=0)
  std_dev = np.std(data, axis=0)

  # Compute correlation matrix
  correlation_matrix = np.corrcoef(data, rowvar=False)

  # Identify outliers using z-scores
  z_scores = np.abs((data - mean) / std_dev)
  outliers = np.where(z_scores > 3)
```
</details>

In [23]:
# Your code here
# Load data from csv file
data = np.genfromtxt('bai3.csv', delimiter=',', skip_header=1)

# Calculate mean
mean = np.mean(data, axis=0)

# Calculate median
median = np.median(data, axis=0)

# Calculate standard deviation
std = np.std(data, axis=0)

# Calculate correlation coefficient
correlation = np.corrcoef(data, rowvar=False)

# Identify outliers using z-score
z_scores = (data - mean) / std
outliers = np.where(np.abs(z_scores) > 3)

# Print results
print("Mean:", mean)
print("Median:", median)
print("Standard deviation:", std)
print("Correlation coefficient:", correlation)
print("Outliers:", outliers)


Mean: [3.42 3.82 6.48 2.72 7.32]
Median: [3.1 3.8 6.7 2.6 7.1]
Standard deviation: [1.56639714 0.59799666 1.25443214 0.75736385 1.32272446]
Correlation coefficient: [[1.         0.47784764 0.89183434 0.61500461 0.94868903]
 [0.47784764 1.         0.81104187 0.97063145 0.71505798]
 [0.89183434 0.81104187 1.         0.88457426 0.98139657]
 [0.61500461 0.97063145 0.88457426 1.         0.79617986]
 [0.94868903 0.71505798 0.98139657 0.79617986 1.        ]]
Outliers: (array([], dtype=int64), array([], dtype=int64))


# Bài 4: Thao tác với tensor
Đề cho một tensor đại diện cho một hình ảnh thang độ xám. Thực hiện các thao tác sau:

1. Reshape: Reshape tensor thành một hình dạng khác trong khi vẫn đảm bảo tổng số phần tử không đổi.
2. Transpose: Transpose tensor dọc theo các trục được chỉ định.
3. Slice: Trích xuất một tập hợp con của tensor bằng cách cắt dọc theo các kích thước được chỉ định.
4. Concatenate: Concatenate nhiều tensor dọc theo các trục được chỉ định.
5. Các phép toán theo phần tử: Thực hiện các phép toán theo phần tử như cộng, trừ, nhân và chia với các giá trị vô hướng hoặc các tensor khác.
6. Hoạt động rút gọn: Thực hiện các hoạt động rút gọn như tính tổng, trung bình, tối thiểu và tối đa dọc theo các trục được chỉ định.
7. Indexing: Truy cập các phần tử riêng lẻ hoặc các tensor phụ bằng cách sử dụng các chỉ số nguyên hoặc boolean mark.

<details>
  <summary>Hint</summary>

  ```python
    # 1. Reshape the tensor
    reshaped_tensor = image_tensor.reshape(1, 9)

    # 2. Transpose the tensor
    transposed_tensor = image_tensor.T

    # 3. Slice the tensor
    sliced_tensor = image_tensor[:2, :2]

    # 4. Concatenate tensors
    concatenated_tensor = np.concatenate((image_tensor, image_tensor), axis=0)

    # 5. Element-wise operations
    added_tensor = image_tensor + 0.1
    multiplied_tensor = image_tensor * 2

    # 6. Reduction operations
    sum_tensor = np.sum(image_tensor)
    mean_tensor = np.mean(image_tensor, axis=0)
    max_tensor = np.max(image_tensor, axis=1)

    # 7. Indexing
    element = image_tensor[1, 2]
  ```
</details>

In [25]:
image_tensor = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9]
])

In [32]:
# your code here
# Reshape 
reshape_tensor = np.reshape(image_tensor, (1, 9))

# Transpose
transpose_tensor = np.transpose(image_tensor)

# Slice vertical
slice_tensor = image_tensor[:2, :2]

# Concatenate
concat_tensor = np.concatenate((image_tensor, image_tensor), axis=1)

# Element-wise operations
add_tensor = image_tensor + 0.5
multiply_tensor = image_tensor * 2
subtract_tensor = image_tensor - 0.5
divide_tensor = image_tensor / 2

# Reduction operations
sum_tensor = np.sum(image_tensor)
mean_tensor = np.mean(image_tensor)
max_tensor = np.max(image_tensor)
min_tensor = np.min(image_tensor)

# Indexing
element = image_tensor[1, 1]
