In [1]:
import numpy as np
np.random.seed(42)

# Problem 1: Tạo hai ma trận 3x3 với các phần tử integer ngẫu nhiên từ 1 - 10.

In [7]:
# Your code here
np_array_1 = np.random.randint(1, 10, size=(3, 3))
np_array_2 = np.random.randint(1, 10, size=(3, 3))

print("Ma trận 1:", np_array_1)
print("Ma trận 2:", np_array_2)

Ma trận 1: [[3 1 5]
 [7 9 7]
 [9 8 2]]
Ma trận 2: [[1 7 7]
 [8 5 3]
 [8 6 3]]


# Problem 2: Thực hiện phép cộng phần tử, nhân từng phần tử, tích vô hướng với hai ma trận vừa được tạo.


In [8]:
# Your code here
sum_array = np_array_1 + np_array_2
print("Tổng 2 ma trận:", sum_array)

multi_array = np_array_1 * np_array_2
print("Nhân 2 ma trận:", multi_array)

dot_product = np.dot(np_array_1, np_array_2)
print("Tích vô hướng 2 ma trận:", dot_product)


Tổng 2 ma trận: [[ 4  8 12]
 [15 14 10]
 [17 14  5]]
Nhân 2 ma trận: [[ 3  7 35]
 [56 45 21]
 [72 48  6]]
Tích vô hướng 2 ma trận: [[ 51  56  39]
 [135 136  97]
 [ 89 115  93]]


# Problem 3: VIết hàm nhận vào một mảng Numpy, sau đó trả về tổng tất cả các phần tử của chúng


In [11]:
# Your code here
def sum_elements(matrix):
    return np.sum(matrix)

matrix = np.random.randint(1, 10, size=(3, 3))
print("Ma trận:", matrix)
print("Tổng tất cả các phàn tử của ma trận:", sum_elements(matrix))

Ma trận: [[7 3 6]
 [2 9 5]
 [6 4 7]]
Tổng tất cả các phàn tử của ma trận: 49
